test

diff --git a/.github/workflows/vtest.yml b/.github/workflows/vtest.yml
--- a/.github/workflows/vtest.yml
+++ b/.github/workflows/vtest.yml
@@ -60,7 +60,12 @@ jobs:
     - name: Generate cache key
       id: generate-cache-key
       run: |
-        if ! [[ ${{ matrix.name }} =~ "QUICTLS_COMMIT" ]] 2> /dev/null && [[ ${{ matrix.name }} =~ "quic" ]]; then (echo "QUICTLS_COMMIT is missing"; exit 1); fi
+
+        if ! [[ ${{ matrix.name }} =~ "QUICTLS_COMMIT" ]] 2> /dev/null && [[ ${{ matrix.name }} =~ "quic" ]]; then
+          echo "QUICTLS_COMMIT is missing"
+          exit 1
+        fi
+
         echo "key=$(echo ${{ matrix.name }} | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
 
     - name: Cache SSL libs
