CI: enable QuicTLS cache

diff --git a/.github/workflows/vtest.yml b/.github/workflows/vtest.yml
--- a/.github/workflows/vtest.yml
+++ b/.github/workflows/vtest.yml
@@ -56,14 +56,21 @@ jobs:
 
 #
 # Github Action cache key cannot contain comma, so we calculate it based on job name
+# job name must has either SSL lib version or commit hash to be unique
 #
     - name: Generate cache key
       id: generate-cache-key
       run: |
+
+        if ! [[ "${{ matrix.name }}" =~ "QUICTLS_COMMIT" ]] 2> /dev/null && [[ "${{ matrix.name }}" =~ "quic" ]]; then
+          echo "QUICTLS_COMMIT is missing"
+          exit 1
+        fi
+
         echo "key=$(echo ${{ matrix.name }} | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
 
     - name: Cache SSL libs
-      if: ${{ matrix.ssl && matrix.ssl != 'stock' && matrix.ssl != 'BORINGSSL=yes' && matrix.ssl != 'QUICTLS=yes' }}
+      if: ${{ matrix.ssl && matrix.ssl != 'stock' && matrix.ssl != 'BORINGSSL=yes' }}
       id: cache_ssl
       uses: actions/cache@v4
       with:
@@ -97,7 +104,7 @@ jobs:
         scripts/build-vtest.sh
     - name: Install SSL ${{ matrix.ssl }}
       if: ${{ matrix.ssl && matrix.ssl != 'stock' && steps.cache_ssl.outputs.cache-hit != 'true' }}
-      run: env ${{ matrix.ssl }} scripts/build-ssl.sh
+      run: env ${{ matrix.ssl }} QUICTLS_COMMIT=${{ contains(matrix.name, 'QUICTLS_COMMIT') && matrix.QUICTLS_COMMIT || '' }}  scripts/build-ssl.sh
     - name: Install OpenTracing libs
       if: ${{ contains(matrix.FLAGS, 'USE_OT=1') && steps.cache_ot.outputs.cache-hit != 'true'  }}
       run: |
